#!/usr/bin/env python3
#
# EPITECH PROJECT, 2024
# zappy
# File description:
# This file start the ai client
#

import sys
from main import main

if __name__ == "__main__":
    exit(main(sys.argv[1:]))
