/*
** EPITECH PROJECT, 2024
** zappy
** File description:
** Incantation
*/

#pragma once

#define INCANTATION_SPHERE_RINGS 100
#define INCANTATION_SPHERE_SEGMENTS = INCANTATION_SPHERE_RINGS
#define INCANTATION_SPHERE_SPEED 6.0f
#define INCANTATION_SPHERE_RADIUS 1.0f
#define INCANTATION_SPHERE_MAX_RADIUS 5.0f
